export default {
  USER_REGISTER: 'USER_REGISTER',
  PRODUCTS_LIST: 'PRODUCTS_LIST',
  SINGLE_PRODUCT: 'SINGLE_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  CLEAN_PRODUCT: 'CLEAN_PRODUCT',
  REVIEWS_LIST: 'REVIEWS_LIST',
  CREATE_REVIEW: 'CREATE_REVIEW'
}
